### ISSUE TITLE
Task2_4 мульти-параметрическая сортировка

### ISSUE THREAD

**Issue by Fursanov** [kz306438/TaskSolutions#2]
[Task2_4](https://github.com/kz306438/TaskSolutions/blob/main/Task2_4/src/main/java/org/example/FileSorterTestClient.java)
Программа должна иметь возможность сортировать файлы сразу по нескольким параметрам одновременно. Например, я пишу -stn и программа сортирует сначала по размеру, файлы с одинаковым размером сортирует по дате, а файлы с одинаковым размером и дате сортирует по времени.

**Comment by kz306438** [comment]
Исправил, теперь появилась возможность сортировки файла сразу по нескольким параметрам

**Comment by Fursanov** [comment]
Ах да, исправь фактически затраченное время в табличке на эту задачу если конечно оно значительное
