### ISSUE TITLE
Task3_2 Несоответствие ожидания и результата

### ISSUE THREAD

**Issue by Fursanov** [kz306438/TaskSolutions#3]
https://github.com/kz306438/TaskSolutions/blob/da08e00f20cafeb2cc4e61bb16607771c6bbcdb5/Task3_2/src/main/java/org/isordered/BinarySearchTreeTest.java#L44

![Снимок экрана от 2024-11-20 10-38-20](https://github.com/user-attachments/assets/a4839859-9683-4c43-8436-c282bf6661c1)

Неувязочка в последнем тесте. Так-то программа работает корректно, так как с подобным условием вставки такое дерево не может не пройти по заданному условию. Но комментарий говорит об обратном, странно.

**Comment by kz306438** [comment]
Убаран некорректный тест

**Comment by Fursanov** [comment]
Так, на будущее, issue закрываю я)
