### ISSUE TITLE
Task5_2 Некорректный ресайз при удалении элементов

### ISSUE THREAD

**Issue by Fursanov** [kz306438/TaskSolutions#6]
[Task5_2](https://github.com/kz306438/TaskSolutions/tree/main/Task5_2)

![image](https://github.com/user-attachments/assets/8543efa3-9162-4a9a-a1da-aa89713323c6)

![image](https://github.com/user-attachments/assets/6e0f63b8-ded3-4883-9a81-2e8f3564d610)

Ресайз в удалении никогда не будет вызван так как не происходит декремента параметра n и ресайз в большую сторону в данном случае растет с большей скоростью чем в меньшую. 

Возможно стоит оценивать параметром n ненулевые пары ключ-значение, этого можно добиться декрементом параметра n после инкремента nullCount в методе удаления. 

Еще один вариант в проверке на ресайз в методе удаления вместо `(n > 0 && n <= m / 8)` сделать `(n - nullCount > 0 && n - nullCount <= m / 8)` , но тогда после очищения нулевых пар в методе ресайза нужно будет отнимать от n значение nullCount перед занулением, так как эти удаленные элементы при добавлении внесли свой вклад в значение n, а после очищения самих элементов уже нет (даже нулевых пар), а значение n все равно считает как будто они есть.

Также возможно стоит немного уменьшить шаг для ресайза таблицы в меньшую сторону, при этом добавить некоторый минимальный размер ниже которого нельзя будет опуститься.

Это лишь пару вариантов решения проблемы из множества, сам ты можешь исправить и по своему.

**Comment by kz306438** [comment]
Теперь ресайз работает корректно. Уменьшил шаг ресайза. Задал минимальный размер таблицы.

**Comment by Fursanov** [comment]
Отлично! Принято.
